import React from 'react';

const InventoryReport = ({ data }) => {
  const currentDate = new Date().toLocaleDateString();
  const totalItems = data.reduce((sum, item) => sum + item.stock, 0);
  const lowStockItems = data.filter(item => item.stock < item.minStock);

  return (
    <div className="report-container" id="inventory-report">
      <div className="report-header">
        <h1>Inventory Report</h1>
        <div className="report-meta">
          <p><strong>Generated:</strong> {currentDate}</p>
          <p><strong>Total Items:</strong> {totalItems}</p>
          <p><strong>Low Stock Alerts:</strong> {lowStockItems.length}</p>
        </div>
      </div>
      
      <div className="report-content">
        <h3>Current Inventory Status</h3>
        <table className="inventory-table">
          <thead>
            <tr>
              <th>Product Name</th>
              <th>SKU</th>
              <th>Current Stock</th>
              <th>Min Stock</th>
              <th>Status</th>
              <th>Last Updated</th>
            </tr>
          </thead>
          <tbody>
            {data.map((item, index) => (
              <tr key={index} className={item.stock < item.minStock ? 'low-stock' : ''}>
                <td>{item.name}</td>
                <td>{item.sku}</td>
                <td>{item.stock}</td>
                <td>{item.minStock}</td>
                <td>
                  <span className={`status ${item.stock < item.minStock ? 'low' : 'normal'}`}>
                    {item.stock < item.minStock ? 'Low Stock' : 'Normal'}
                  </span>
                </td>
                <td>{item.lastUpdated}</td>
              </tr>
            ))}
          </tbody>
        </table>
        
        {lowStockItems.length > 0 && (
          <div className="alert-section">
            <h3>Low Stock Alerts</h3>
            <ul>
              {lowStockItems.map((item, index) => (
                <li key={index}>
                  <strong>{item.name}</strong> - Current: {item.stock}, Min: {item.minStock}
                </li>
              ))}
            </ul>
          </div>
        )}
      </div>
      
      <div className="report-footer">
        <p>Report generated by React PDF Export System</p>
      </div>
    </div>
  );
};

export default InventoryReport;