import React from 'react';

const SalesReport = ({ data }) => {
  const currentDate = new Date().toLocaleDateString();
  const totalSales = data.reduce((sum, item) => sum + item.amount, 0);

  return (
    <div className="report-container" id="sales-report">
      <div className="report-header">
        <h1>Sales Report</h1>
        <div className="report-meta">
          <p><strong>Generated:</strong> {currentDate}</p>
          <p><strong>Total Sales:</strong> ${totalSales.toLocaleString()}</p>
        </div>
      </div>
      
      <div className="report-content">
        <table className="sales-table">
          <thead>
            <tr>
              <th>Product</th>
              <th>Quantity</th>
              <th>Unit Price</th>
              <th>Total Amount</th>
              <th>Date</th>
            </tr>
          </thead>
          <tbody>
            {data.map((item, index) => (
              <tr key={index}>
                <td>{item.product}</td>
                <td>{item.quantity}</td>
                <td>${item.unitPrice.toFixed(2)}</td>
                <td>${item.amount.toFixed(2)}</td>
                <td>{item.date}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      
      <div className="report-footer">
        <p>Report generated by React PDF Export System</p>
      </div>
    </div>
  );
};

export default SalesReport;